# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift

target 'HW9' do

pod 'SwiftyJSON', '~> 2.3'
pod 'CCAutocomplete', '~> 0.0.4'

use_frameworks!
end

